### ISSUE TITLE
Ignored byte_order setting

### ISSUE THREAD

**Issue by anamud** [efficios/babeltrace#54]
Hi, 

I am using BabelTrace Trace Viewer and Converter 2.0.0-pre. The trace writer is ignoring the byte order set explicitly to big endian and reverting to the native little endian byte order. 

Can you please help debug this problem?

I have attached my test script as a zipped archive
[test-script.zip](https://github.com/efficios/babeltrace/files/851310/test-script.zip)
. 

Below is the shell output when the test script is executed and tested on my machine, a Thinkpad T460s with Ubuntu 16.04.

```
ananya@samruddha:~$ grep "BIG_ENDIAN" ./test.py
writer.byte_oder =  babeltrace.common.ByteOrder.BYTE_ORDER_BIG_ENDIAN
ananya@samruddha:~$ ./test.py 
Wrote to /tmp/tmpjeing2ef
ananya@samruddha:~$ cat /tmp/tmpjeing2ef/metadata | head
/* CTF 1.8 */

trace {
	major = 1;
	minor = 8;
	uuid = "edaacbcf-3117-407b-9573-5e14117cfb67";
	byte_order = le;
	packet.header := struct {
		integer { size = 32; align = 8; signed = false; encoding = none; base = decimal; byte_order = le; } magic;
		integer { size = 8; align = 8; signed = false; encoding = none; base = decimal; byte_order = le; } uuid[16];
ananya@samruddha:~$ cat /tmp/tmpjeing2ef/metadata | tail
event {
	id = 0;
	name = "the_event";
	stream_id = 0;
	fields := struct {
		string { encoding = UTF8; } string_field;
		integer { size = 32; align = 1; signed = false; encoding = none; base = decimal; byte_order = le; } uint32_field;
	} align(8);
};

ananya@samruddha:~$ 
```

**Comment by jgalar** [comment]
Hi @anamud!

Thanks for reporting this bug. Would you mind opening it on the official bug tracker?
https://bugs.lttng.org/projects/babeltrace/issues

It seems we forgot to disable Issue Tracking on the GitHub project page.

**Comment by jgalar** [comment]
Closing as per https://bugs.lttng.org/issues/1093#change-3183
